# Configuration for Learnable Gated Pooling experiment

# Model parameters
model:
  input_dim: 768  # BERT embedding dimension
  seq_len: 10    # Maximum sequence length

# Training parameters
training:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.001
  device: 'cuda'  # Use 'cpu' if CUDA is not available

# Data parameters
data:
  train_val_split: 0.8  # 80% training, 20% validation
  
# Logging
logging:
  log_file: 'logs/logs.txt'
  log_level: 'INFO'
