model:
  input_dim: 768
  seq_len: 10

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  device: cuda

data:
  train_path: data/train.pt
  val_path: data/val.pt
  test_path: data/test.pt
