model:
  name: "SimpleCNN"
  in_channels: 1
  num_classes: 10

training:
  epochs: 10
  batch_size: 128
  learning_rate: 0.001
  optimizer:
    name: "AdvancedOptimizer"
    betas: [0.0, 0.9, 0.99]
    momentum: 0.9
    weight_decay: 0.0001
    eps: 1e-6

data:
  dataset: "MNIST"
  train_split: 0.8
  val_split: 0.2
