name: Run Experiment

on:
  push:
    branches:
      - 'devin/**'

defaults:
  run:
    shell: bash

jobs:
  execution-of-automated-research-methods:
    name: Execution of automated research methods
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run experiment
        run: python src/main.py > data/output.log 2> data/error.log
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: output file
          path: data/output.log
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
            name: error file
            path: data/error.log
            retention-days: 1
