name: Run Experiment

on:
  push:
    branches:
      - 'devin/**'

defaults:
  run:
    shell: bash

jobs:
  execution-of-automated-research-methods:
    name: Execution of automated research methods
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - uses: actions/upload-artifact@v4
        with:
          name: requirements file 2
          path: requirements.txt
          retention-days: 1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run experiment
        run: python src/main.py
