name: Run Experiment

on:
  push:
    branches:
      - 'devin/**'

defaults:
  run:
    shell: bash

jobs:
  runnning-automated-research:
    name: Running automated research
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run experiment
        run: python src/main.py
